/*
 * Ara Platform
 *
 * Ara is a server platform that can deploy Tyk and it's various components into multiple control planes such as K8s and CloudFormation. It is modular and designed to be extended to support multiple specific operational deployments, DNS providers and underlying storage providers
 *
 * API version: v0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type HealthReport struct {
	CPStatusMeta map[string]interface{} `json:"CPStatusMeta,omitempty"`
	ControlPlaneStatus string `json:"ControlPlaneStatus,omitempty"`
	ServerID string `json:"ServerID,omitempty"`
	Status string `json:"Status,omitempty"`
	StorageStatus string `json:"StorageStatus,omitempty"`
	StoreStatusMeta map[string]interface{} `json:"StoreStatusMeta,omitempty"`
}
