/*
 * Ara Platform
 *
 * Ara is a server platform that can deploy Tyk and it's various components into multiple control planes such as K8s and CloudFormation. It is modular and designed to be extended to support multiple specific operational deployments, DNS providers and underlying storage providers
 *
 * API version: v0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Entitlements struct {
	// Counters represent a maximum of a class that can be consumed.
	Counters map[string]CounterEntitlement `json:"Counters,omitempty"`
	Region   *RegionEntitlement            `json:"Region,omitempty"`
	// Runtimes represent abstract resources consumed by deployed stacks  In Phase 1: Control Plane deployments consume runtimes at the organisation level Edge deployments consume runtimes at the loadout/environment level
	Runtimes map[string]RuntimeEntitlement `json:"Runtimes,omitempty"`
	// Toggles represent values that can be either on or off.
	Toggles map[string]EnabledEntitlement `json:"Toggles,omitempty"`
	Values  *map[string]interface{}       `json:"Values,omitempty"`
}
