/*
 * Ara Platform
 *
 * Ara is a server platform that can deploy Tyk and it's various components into multiple control planes such as K8s and CloudFormation. It is modular and designed to be extended to support multiple specific operational deployments, DNS providers and underlying storage providers
 *
 * API version: v0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

// OrgTrafficReport represents the total requests grouped by organisation ID (i.e. a total of all deployment traffic reports).
type OrgTrafficReport struct {
	Date time.Time `json:"Date,omitempty"`
	HomeDeploymentCount int64 `json:"HomeDeploymentCount,omitempty"`
	Kind string `json:"Kind,omitempty"`
	OrgName string `json:"OrgName,omitempty"`
	OrgUID string `json:"OrgUID,omitempty"`
	Processed time.Time `json:"Processed,omitempty"`
	Teams int64 `json:"Teams,omitempty"`
	// The Total field should not be accessed directly, instead use the helper methods; GetTotal & SetTotal
	Total int64 `json:"Total,omitempty"`
}
