/*
 * Ara Platform
 *
 * Ara is a server platform that can deploy Tyk and it's various components into multiple control planes such as K8s and CloudFormation. It is modular and designed to be extended to support multiple specific operational deployments, DNS providers and underlying storage providers
 *
 * API version: v0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type AccessGrant struct {
	// When the access grant expires
	Expires time.Time `json:"Expires,omitempty"`
	// The map of tag-name to encrypted pem-encoded private key
	Keys map[string]Secret `json:"Keys,omitempty"`
	// Set to `true` to skip expiry checks
	NeverExpire bool `json:"NeverExpire,omitempty"`
	// THe ID of the access grant
	UID string `json:"UID,omitempty"`
}
