/*
 * Ara Platform
 *
 * Ara is a server platform that can deploy Tyk and it's various components into multiple control planes such as K8s and CloudFormation. It is modular and designed to be extended to support multiple specific operational deployments, DNS providers and underlying storage providers
 *
 * API version: v0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Broadly based around AWS EC2 instance types in Phase 1: https://aws.amazon.com/ec2/instance-types/ Further abstractions based on other platforms (GCP, Azure, Alibaba, et al) will be forthcoming.
type RuntimeEntitlement struct {
	Allowed int64 `json:"Allowed,omitempty"`
	Consumed int64 `json:"Consumed,omitempty"`
	Name string `json:"Name,omitempty"`
	Values *map[string]interface{} `json:"Values,omitempty"`
}
