# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private"
class Tykctl < Formula
  desc "Tykctl homebrew"
  homepage "https://github.com/TykTechnologies/tykctl"
  version "0.0.10"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TykTechnologies/tykctl/releases/download/v0.0.10/tykctl_0.0.10_Darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "c2778aedc3652d735485bb019fb0fea9cec5ab782b22eb6193d1ef97ec1dc460"

      def install
        bin.install "tykctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TykTechnologies/tykctl/releases/download/v0.0.10/tykctl_0.0.10_Darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "25637bad21aabe2b288b6b498f8fa7a3308556a3db20cb357079ecdfd69baa71"

      def install
        bin.install "tykctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TykTechnologies/tykctl/releases/download/v0.0.10/tykctl_0.0.10_Linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "67fcc4e6c5a910d0645eb92416e65d3f09d72db7d5ca8859bc06b1309bf4ec98"

      def install
        bin.install "tykctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/TykTechnologies/tykctl/releases/download/v0.0.10/tykctl_0.0.10_Linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "1bc6d2d15020c168c260d402644050c7b1ea0a3f0e0b85eadd46459c801178d3"

      def install
        bin.install "tykctl"
      end
    end
  end
end
