package cmd

const (
	statusOK               = "ok"
	list                   = "list"
	fetch                  = "fetch"
	applicationJson        = "application/json"
	loginPath              = "/api/login"
	login                  = "login"
	cookieAuthorisation    = "cookieAuthorisation"
	signature              = "signature"
	dashboard              = "dashboard"
	email                  = "email"
	password               = "password"
	baUser                 = "ba-user"
	baPass                 = "ba-pass"
	token                  = "token"
	contentType            = "Content-Type"
	teamEntitlement        = "MaxTeamCount"
	environmentEntitlement = "MaxLoadoutCount"
	dashboardEntitlement   = "MaxDashboardCount"
	gatewayEntitlement     = "MaxGatewayCount"
	outPut                 = "output"
	table                  = "table"
	jsonFormat             = "json"
	team                   = "team"
	teams                  = "teams"
	create                 = "create"
	name                   = "name"
	org                    = "org"
)
