package cmd

const (
	statusOK               = "ok"
	list                   = "list"
	fetch                  = "fetch"
	applicationJson        = "application/json"
	loginPath              = "/api/login"
	login                  = "login"
	cookieAuthorisation    = "cookieAuthorisation"
	signature              = "signature"
	dashboard              = "dashboard"
	email                  = "email"
	password               = "password"
	baUser                 = "ba-user"
	baPass                 = "ba-pass"
	token                  = "token"
	contentType            = "Content-Type"
	teamEntitlement        = "MaxTeamCount"
	environmentEntitlement = "MaxLoadoutCount"
	dashboardEntitlement   = "MaxDashboardCount"
	gatewayEntitlement     = "MaxGatewayCount"
	outPut                 = "output"
	table                  = "table"
	jsonFormat             = "json"
	team                   = "team"
	teams                  = "teams"
	create                 = "create"
	name                   = "name"
	org                    = "org"
	environments           = "environments"
	home                   = "home"
	edge                   = "edge"
	deployment             = "deployment"
	env                    = "env"
	zone                   = "zone"
	domain                 = "domain"
	gateway                = "Gateway"
	controlPlane           = "Home"
	awsKeyID               = "aws-key-id"
	awsSecret              = "aws-secret"
	awsRegion              = "aws-region"
	enablePlugins          = "enable-plugins"
	linkedControlPlane     = "control-plane"
)
