/*
 * Ara Platform
 *
 * Ara is a server platform that can deploy Tyk and it's various components into multiple control planes such as K8s and CloudFormation. It is modular and designed to be extended to support multiple specific operational deployments, DNS providers and underlying storage providers
 *
 * API version: v0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// MetaDataStore represents a storage object for metadata related to a deployment or driver (control plane), using annotations (tags) to create a key space, and then within the second tier hierarchy another map, to interfaces. The reason this is not a plain map of maps is for readability and clarity when using it, as the syntax of maps can get very confusing, especially with type assertions. TODO: This is a prime target for re-design.
type MetaDataStore struct {
	Data map[string]map[string]interface{} `json:"Data,omitempty"`
}
