/*
 * Ara Platform
 *
 * Ara is a server platform that can deploy Tyk and it's various components into multiple control planes such as K8s and CloudFormation. It is modular and designed to be extended to support multiple specific operational deployments, DNS providers and underlying storage providers
 *
 * API version: v0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"time"
)

type EntitlementPlan struct {
	// Counters represent a maximum of a class that can be consumed.
	Counters map[string]CounterEntitlement `json:"Counters,omitempty"`
	// Not used
	Default_ bool `json:"Default,omitempty"`
	// Last time the plan was changed
	LastUpdated time.Time `json:"LastUpdated,omitempty"`
	// Human-readable name of the plan
	Name   string             `json:"Name,omitempty"`
	Region *RegionEntitlement `json:"Region,omitempty"`
	// Runtimes represent abstract resources consumed by deployed stacks  In Phase 1: Control Plane deployments consume runtimes at the organisation level Edge deployments consume runtimes at the loadout/environment level
	Runtimes map[string]RuntimeEntitlement `json:"Runtimes,omitempty"`
	// Toggles represent values that can be either on or off.
	Toggles map[string]EnabledEntitlement `json:"Toggles,omitempty"`
	// ID of the plan
	UID    string                  `json:"UID,omitempty"`
	Values *map[string]interface{} `json:"Values,omitempty"`
	// Zone tag, not stored, but populated implicitly
	Zone string `json:"Zone,omitempty"`
}
