/*
 * Ara Platform
 *
 * Ara is a server platform that can deploy Tyk and it's various components into multiple control planes such as K8s and CloudFormation. It is modular and designed to be extended to support multiple specific operational deployments, DNS providers and underlying storage providers
 *
 * API version: v0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Represents a directional access grant creation without providing a public key
type Challenge struct {
	// A map of `tag:password`, the password will be used to re-encrypt the Access Grant of `ServerUID` as a new grant
	Keys map[string]string `json:"Keys,omitempty"`
	// The Access Grant ID of the access grant used by the server
	ServerUID string `json:"ServerUID,omitempty"`
}
