/*
 * Ara Platform
 *
 * Ara is a server platform that can deploy Tyk and it's various components into multiple control planes such as K8s and CloudFormation. It is modular and designed to be extended to support multiple specific operational deployments, DNS providers and underlying storage providers
 *
 * API version: v0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Team is the second-highest grouping object, under Organisation
type Team struct {
	// Blocked when true blocks the team's deployments from functioning depending on their kind
	Blocked      bool           `json:"Blocked,omitempty"`
	Entitlements *Entitlements  `json:"Entitlements,omitempty"`
	ExtraContext *MetaDataStore `json:"ExtraContext,omitempty"`
	// Frozen when true prevents non-admin write operations on the team
	Frozen bool `json:"Frozen,omitempty"`
	// The team Loadouts (collections of deployments) The Loadouts field should not be accessed directly, instead use the helper methods; SetLoadout & AppendLoadout
	Loadouts []Loadout `json:"Loadouts,omitempty"`
	// The human-readable name of the team
	Name string `json:"Name"`
	// Organisation ID
	OID          string            `json:"OID,omitempty"`
	Organisation *TeamOrganisation `json:"Organisation,omitempty"`
	// The unique ID of the team
	UID string `json:"UID,omitempty"`
}
