/*
 * Ara Platform
 *
 * Ara is a server platform that can deploy Tyk and it's various components into multiple control planes such as K8s and CloudFormation. It is modular and designed to be extended to support multiple specific operational deployments, DNS providers and underlying storage providers
 *
 * API version: v0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ChannelManifest struct {
	Bundles      []Bundle          `json:"Bundles,omitempty"`
	Channel      string            `json:"Channel,omitempty"`
	Checksum     string            `json:"Checksum,omitempty"`
	Driver       string            `json:"Driver,omitempty"`
	Kind         string            `json:"Kind,omitempty"`
	Latest       string            `json:"Latest,omitempty"`
	Repositories map[string]string `json:"Repositories,omitempty"`
	Source       string            `json:"Source,omitempty"`
}
