name: Generate docs
on:
  push:
    branches:
      - main
jobs:
  generate-angular-client:
    runs-on: ubuntu-latest
    name: Example
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate documentation
        run: |
          make generate-docs
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: save generated documentation