name: goreleaser
on:
  push:
    tags:
      - '*'
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/TykTechnologies/cloud-sdk
      GH_ACCESS_TOKEN: ${{ secrets.ORG_GH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          version: latest
          args: -f .goreleaser.yaml release --rm-dist

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Your GoReleaser Pro key, if you are using the 'goreleaser-pro' distribution

          # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
      - name: Upload assets
        uses: actions/upload-artifact@v3
        with:
          name: tykctl
          path: dist/*
