name: Test the code

on:
  push:
    branches:
      - "*"
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          stable: 'false'
          go-version: '1.19'

      - name: Testing
        run: make test