name: Test the code and run sonal cloud

on:
  push:
    branches:
      - "*"
jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      GOPRIVATE: github.com/TykTechnologies
    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@d72941d797fd3113feb6b93fd0dec494b13a2547 # v1
        with:
          app-id: ${{ secrets.PROBE_APP_ID }}
          private-key: ${{ secrets.PROBE_APP_PRIVATE_KEY }}
          owner: TykTechnologies

      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          stable: 'false'
          go-version: '1.19'

      - name: Configure Git for private modules
        env:
          TOKEN: ${{ steps.app-token.outputs.token }}
        run: git config --global url.https://x-access-token:${TOKEN}@github.com/.insteadOf https://github.com/
      - name: Testing
        run: make tests