name: Test the code and run sonal cloud

on:
  push:
    branches:
      - "*"
jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      GOPRIVATE: github.com/TykTechnologies/cloud-sdk
      GH_ACCESS_TOKEN: ${{ secrets.ORG_GH_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          stable: 'false'
          go-version: '1.19'

      - run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/
      - name: Testing
        run: make tests
      #- name: Check Test coverage with Sonar cloud
        #uses: sonarsource/sonarcloud-github-action@master
        #env:
        #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         # SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}